local Plugins = {
  "folke/which-key.nvim",
  "folke/neodev.nvim",
  -- 'hrsh7th/cmp-nvim-lsp',
  -- 'hrsh7th/cmp-buffer',
  -- 'hrsh7th/cmp-path',
  -- 'hrsh7th/cmp-cmdline',
  -- 'hrsh7th/nvim-cmp',
  ---- "lukas-reineke/lsp-format.nvim",
  -- "williamboman/mason.nvim",
  -- "williamboman/mason-lspconfig.nvim",
  -- "neovim/nvim-lspconfig",
  -- 'jose-elias-alvarez/null-ls.nvim' -- RIP
  -- ColorSchemes
  'wuelnerdotexe/vim-enfocado',
  'nanotech/jellybeans.vim',
  'luisiacc/gruvbox-baby',
  'prettier/vim-prettier',
  'tpope/vim-markdown',
  'tpope/vim-fugitive',
  'tpope/vim-commentary',
  'sheerun/vim-polyglot',
  'tpope/vim-rhubarb',
  'scrooloose/nerdtree',
  'bronson/vim-trailing-whitespace',
  'ryanoasis/vim-devicons',
  'mhinz/vim-signify',
  'jiangmiao/auto-pairs',
  'easymotion/vim-easymotion',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'kyazdani42/nvim-web-devicons',
  'folke/which-key.nvim',
  'akinsho/toggleterm.nvim',
  'justinmk/vim-sneak',
  'liuchengxu/vista.vim',
  'cedarbaum/fugitive-azure-devops.vim',
  'MunifTanjim/prettier.nvim',
  'tpope/vim-surround',
  'kdheepak/lazygit.nvim',
  "RRethy/vim-illuminate",
  "lewis6991/gitsigns.nvim",
  'antoinemadec/FixCursorHold.nvim',
  "github/copilot.vim",
  "prisma/vim-prisma",
  "mfussenegger/nvim-lint",
  'nvim-tree/nvim-tree.lua',
  "lewis6991/hover.nvim",
  'fannheyward/telescope-coc.nvim',
  'xiyaowong/coc-code-action-menu.nvim',
  "tiagovla/scope.nvim",
  'akinsho/bufferline.nvim',
  'nvim-lualine/lualine.nvim',
  'nvim-telescope/telescope-fzf-native.nvim',
  "folke/trouble.nvim",
  'nvim-treesitter/nvim-treesitter',
  { "folke/neoconf.nvim", cmd = "Neoconf" },
  { "neoclide/coc.nvim",  branch = 'release' },
  {
    'weilbith/nvim-code-action-menu',
    cmd = 'CodeActionMenu'
  },
  { 'airblade/vim-gitgutter', branch = 'main' },
}

return Plugins
