#!/bin/bash
title="Opinionated Quick Setups"
prompt="Pick an option:"
options=("A" "B" "C")

echo "$title"
PS3="$prompt "
options=("Install Ubuntu Applications" "Install rPI Applications" "Install Mac Applications" "Install VPS Applications" "Install Windows Apps" "vim - load ubuntu vim files" "vim - load rPI files" "vim - load mac files" "vim - load vps files" "Use Standard Keyboard" "Use Mac Keyboard" "Quickload Vim Config" "NPM Permission Fix *********Ubuntu/Debian ONLY**********" "Clear your Dotfiles" "Quit")
select opt in "${options[@]}"
do
  case $opt in
    "Install Ubuntu Applications")
      echo "Installing Ubuntu Apps..."
      sh ubuntu/apps.sh
      break
      ;;
    "Install rPI Applications")
      echo "Installing rPI Apps..."
      sh pi/apps.sh
      break
      ;;
    "Install Mac Applications")
      echo "Installing Mac Apps"
      sh mac/apps.sh
      break
      ;;
    "Install VPS Applications")
      echo "Installing VPS Apps"
      sh ubuntu/apps.sh
      break
      ;;
    "Install Windows Apps")
      echo "'If Microsoft ever does applications for linux, it means I've won' -Linus Torvalds"
      break
      ;;
    "vim - load ubuntu vim files")
      echo "loading vim plugins..."
      cd ubuntu && sh cpdotfiles.sh
      break
      ;;
    "vim - load rPI files")
      echo "loading vim plugins..."
      cd pi && sh cpdotfiles.sh &
      break
      ;;
    "vim - load mac files")
      echo "loading vim plugins..."
      cd mac && sh cpdotfiles.sh &
      break
      ;;
    "vim - load vps files")
      echo "loading vim files..."
      cd .vps && sh cpdotfiles.sh
      break
      ;;
    "Use Standard Keyboard")
      echo "Xmodmap standard keyboard"
      xmodmap .Xmodmap.ubuntu &
      break
      ;;
    "Use Mac Keyboard")
      echo "Xmodmap for mac keyboard"
      xmodmap .Xmodmap.mac &
      break
      ;;
    "Quickload dotfiles")
      echo "Quickload Vim Config"
      sh universal/quickload.sh
      break
      ;;
    "NPM Permission Fix *********Ubuntu/Debian ONLY**********")
      echo "Fixing Permissions"
      sh ubuntu/fixnpm.sh
      break
      ;;
    "Clear your Dotfiles")
      echo "Clearing dotfiles..."
      rm -rf ~/.vim ~/.vimrc ~/.tmux.conf ~/.zshrc ~/.eslintrc ~/.ctags &
      break
      ;;
    "Quit")
      break
      ;;
    *) echo invalid option;;
  esac
done
